In [1]:
import torch


In [2]:
X = torch.tensor([[1,4,7], [2,3,6]])
X

tensor([[1, 4, 7],
        [2, 3, 6]])

In [3]:
10 * (X + 1.0)

tensor([[20., 50., 80.],
        [30., 40., 70.]])

In [4]:
X.exp()

tensor([[   2.7183,   54.5981, 1096.6332],
        [   7.3891,   20.0855,  403.4288]])

In [5]:
X @ X.T

tensor([[66, 56],
        [56, 49]])

In [6]:
X.relu_()

tensor([[1, 4, 7],
        [2, 3, 6]])

In [7]:
if torch.cuda.is_available():
    device = "cuda"
elif torch.backends.mps.is_available():
    device = "mps"
else:
    device = "cpu"

In [8]:
import torch
print(torch.__version__)        # e.g. 2.x.x+cu130
print(torch.version.cuda)       # should be 13.0, not None
print(torch.cuda.is_available())
print(torch.cuda.device_count())


2.12.0+cu130
13.0
True
1


In [9]:
device

'cuda'

In [10]:
M = torch.tensor([[1,2,3], [4,5,6]])

In [11]:
M = M.to("cuda")
M

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')

In [12]:
M = torch.rand((1000,1000))
%timeit M @ M.T
M = torch.rand((1000,1000), device="cuda")
%timeit M @ M.T


3.12 ms ± 37.4 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
63.8 μs ± 3.96 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [13]:
x = torch.tensor(5.0, requires_grad=True)
f = x ** 2
print(f)

f.backward()
print(x.grad)

tensor(25., grad_fn=<PowBackward0>)
tensor(10.)


In [17]:
learning_rate = 0.1
x = torch.tensor(5.0, requires_grad=True)
for i in range(100):
    f = x ** 2
    f.backward()
    with torch.no_grad():
        x -= (learning_rate * x.grad)
    
    x.grad.zero_()
        

In [18]:
x

tensor(1.0185e-09, requires_grad=True)